### ISSUE TITLE
Use kwargs-style method for passing parameters, e.g. for Nearest Neighbors in Kernel Class 

### ISSUE THREAD

**Issue by ehthiede** [DiffusionMapsAcademics/pyDiffMap#9] opened 2017-11-27 19:15 UTC
Rather then naming a few of the technical parameters explicitly, e.g. n_neighbors, we should instead pass a dictionary of arguments that gets handed to the NearestNeighbors object.  This will give much greater flexibility in customizing the neighborlist, while still maintaining a reasonable level of abstraction.

A point of discussion: should we fold 'metric' and 'metric_params' into this?  Theoretically one could, but I feel like this is hiding too much for the user, and we should have 'metric' as an explicit parameter for transparency.

**Comment by ehthiede** [comment] 2017-11-27 19:16
Incidentally, if someone is wondering what I'm talking about re: kwargs, check out the new visualization code (I just learned how to do this today myself).

**Comment by ralfbanisch** [comment] 2017-11-27 21:58
That's a great idea! We should do it this way.

**Comment by ralfbanisch** [comment] 2017-11-27 22:03
And I think yes, we should keep 'metric' and 'metric_params' separate from this.

**Comment by ralfbanisch** [comment] 2017-11-27 22:27
So that raises one question: If no kwargs list is passed by the user, should we use sklearn's defaults then or should we override them with our own defaults? So far, we've used a different default for k (the default for k in sklearn is k=5, ours is k=64.). The argument in favour of the sklearn default is that it's simpler and we can shift the blame to them, or the user, for wrong parameter choices. The argument against it is that k=5 will very rarely be a good choice for diffusion map applications.

**Comment by ralfbanisch** [comment] 2017-11-28 12:39
I created a new branch https://github.com/DiffusionMapsAcademics/pyDiffMap/tree/dev_kwargs

for this. However, there is a problem. When the Neigh() function in kernel.fit(...) is called, I get this error:

/Users/ralfbanisch/Documents/git/pyDiffMap/src/pydiffmap/kernel.py in fit(self, X)
     59             kwargs = self.neighbor_params
     60             self.neigh = NearestNeighbors(metric=self.metric,
---> 61                                           metric_params=self.metric_params,
     62                                           kwargs)
     63         self.neigh.fit(X)

NameError: global name 'neighbor_params' is not defined

**Comment by ralfbanisch** [comment] 2017-11-28 12:41
The notebook swiss_roll reproduces this error, if people want to check it out.

**Comment by ralfbanisch** [comment] 2017-11-28 13:00
I'm not so sure if I like it anyway, as it makes the interface clunkier to handle...

**Comment by ehthiede** [comment] 2017-11-28 14:39
Hmm... Maybe the number of neighbors should be something that is set explicitly, like metric?  That would make it less clunkier.  Because kwargs is a little clunky, maybe we should just use it for obscure things, like nearest-neighbor selection method, ball-tree radius, etc.

-Erik

**Comment by ehthiede** [comment] 2017-11-28 14:50
Also, the code in Swiss roll works for me.  Weird.

-Erik

**Comment by ralfbanisch** [comment] 2017-11-28 14:54
True, that seems to be a problem with my python installation on my macbook, which is fucked up now because I did pip install --uprade /pathtopydiffmap.

It does create problems further down the line though, latest when we call 

K = self.neigh.kneighbors_graph(Y, **self.neighbor_params, mode='distance')

which does seem to ask for a k parameter specifically.

**Comment by ehthiede** [comment] 2017-11-28 15:25
Still not getting those bugs.  Weird.

In any case, let's make k an explicit parameter.  It sounds like that's best all around.

**Comment by ralfbanisch** [comment] 2017-11-28 15:28
Are you sure? The Swiss roll notebook runs also if you uncomment the fit_transform(...) line?

**Comment by ehthiede** [comment] 2017-11-28 15:37
Didn't try that... Will try it once I'm in the office.

Sent from my ASUS

-------- Original Message --------

**Comment by ehthiede** [comment] 2017-11-28 16:08
I get a bug that says:

AttributeError: 'Kernel' object has no attribute 'k0'

But I think that's a coding problem.

**Comment by ralfbanisch** [comment] 2017-11-28 16:17
My suspicion is that it's going to work if we remove the 'n_neighbors = self.k0' argument from

K = self.neigh.kneighbors_graph(Y, n_neighbors=self.k0, mode='distance')

since the default for n_neighbors has already been set for the neigh object during initialisation. That should work (and it should probably be done in any case also in the main code). The question remains if we want it that way - it is a bit clunkier but also more flexible. I suppose it depends how often the user will want to change the k parameter. I ended up changing it all the time since the 'optimal' k really does seem to scale with the number of data points and depend on the specific data set.

Incidentally, that annoyed me enough that I put a radius search option in a separate development branch.

**Comment by ehthiede** [comment] 2017-11-28 16:20
I think we should have a separate k argument: I think optimal k depends strongly on the dimensionality, particularly for fixed bandwidth methods (variable bandwidth methods avoid this problem somewhat.)

-Erik

**Comment by ralfbanisch** [comment] 2017-11-28 16:25
ok, so separate k argument and the rest gets passed on as a keyword list? I think that sounds good, let me change that and push it.

making that tweak I mentioned above indeed fixes the problem btw.

**Comment by ehthiede** [comment] 2017-11-28 16:26
Ya... let's say separate k, metric, and metric_params.

**Comment by ralfbanisch** [comment] 2017-11-28 16:38
pushed, this should work now.

**Comment by ralfbanisch** [comment] 2017-11-28 16:43
The build #106 fails on travis because all the kernel tests fail. They get unexpected keywords that they don't like.

**Comment by ehthiede** [comment] 2017-11-28 16:57
Maybe we could replace it with some parameterization over the neighbor_params?

e.g. 

@pytest.mark.parameterize('neighbor_params',[
    {'algorithm': 'auto'},
    {'algorithm': 'ball_tree'}
]
 
?

Or we could delete it all together, and just create a separate method for testing the kwargs.

**Comment by ralfbanisch** [comment] 2017-11-28 16:58
Let me try it.

**Comment by ralfbanisch** [comment] 2017-11-28 17:04
not happy:

tests/test_kernel.py:13: in <module>
    class TestKernel(object):
tests/test_kernel.py:49: in TestKernel
    @pytest.mark.parameterize('neighbor_params',[{'algorithm': 'auto'},{'algorithm': 'ball_tree'}])
/Applications/anaconda/lib/python3.6/site-packages/_pytest/mark.py:264: in __getattr__
    self._check(name)
/Applications/anaconda/lib/python3.6/site-packages/_pytest/mark.py:279: in _check
    raise AttributeError("%r not a registered marker" % (name,))
E   AttributeError: 'parameterize' not a registered marker

**Comment by ralfbanisch** [comment] 2017-11-28 17:09
fixed this issue, there are two failures remaining:

=========================== short test summary info ============================
FAIL tests/test_kernel.py::TestKernel::()::test_neighborlists[neighbor_params0-k5]
FAIL tests/test_kernel.py::TestKernel::()::test_neighborlists[neighbor_params1-k5]

=================================== FAILURES ===================================
______________ TestKernel.test_neighborlists[neighbor_params0-k5] ______________
tests/test_kernel.py:61: in test_neighborlists
    K_matrix = mykernel.compute(x_values)
src/pydiffmap/kernel.py:89: in compute
    K = self.neigh.kneighbors_graph(Y, mode='distance')
/Applications/anaconda/lib/python3.6/site-packages/sklearn/neighbors/base.py:485: in kneighbors_graph
    X, n_neighbors, return_distance=True)
/Applications/anaconda/lib/python3.6/site-packages/sklearn/neighbors/base.py:343: in kneighbors
    (train_size, n_neighbors)
E   ValueError: Expected n_neighbors <= n_samples,  but n_samples = 11, n_neighbors = 12
______________ TestKernel.test_neighborlists[neighbor_params1-k5] ______________
tests/test_kernel.py:61: in test_neighborlists
    K_matrix = mykernel.compute(x_values)
src/pydiffmap/kernel.py:89: in compute
    K = self.neigh.kneighbors_graph(Y, mode='distance')
/Applications/anaconda/lib/python3.6/site-packages/sklearn/neighbors/base.py:485: in kneighbors_graph
    X, n_neighbors, return_distance=True)
/Applications/anaconda/lib/python3.6/site-packages/sklearn/neighbors/base.py:343: in kneighbors
    (train_size, n_neighbors)
E   ValueError: Expected n_neighbors <= n_samples,  but n_samples = 11, n_neighbors = 12
===================== 2 failed, 68 passed in 3.04 seconds ======================

**Comment by ralfbanisch** [comment] 2017-11-30 13:09
I'm going to close this since it's fixed now.

**Closed by ralfbanisch** 2017-11-30 13:09 UTC
Labels: help wanted
